[ballerina.log]
level = "INFO"

[qhana.qhana_backend]

# Allow all CORS requests from any domain
corsDomains = ["*"]

[qhana.qhana_backend.internalUrlMap]
"(?<=^|https?://)localhost(:[0-9]+)?" = "host.docker.internal$1"

[qhana.qhana_backend.database]
# The config key must be present or ballerina crashes
